### PR TITLE
feat: new setting `injectScriptsAt`

### PR DESCRIPTION
**Pull request by phonzammi**
Alternative to #1740 

@brillout, Please take a look and review this PR

### CODE REVIEW

**Comment by brillout** [comment]
WDYT? Should we merge?

**Comment by phonzammi** [comment]
> WDYT? Should we merge?

I love it. I just leave one review, if it's fine then LGTM :rocket:

**Comment by brillout** [comment]
> https://github.com/vikejs/vike/commit/6bdbe7cc26cd81b45af22a1d3a6426617a5c4470

How about we allow the user to do a mistake but add a warning instead of blocking him?

**Comment by phonzammi** [comment]
Should we? I don't know, I think I'm fine either way.

**Comment by brillout** [comment]
My concern is that the user wants to change the scripts position (otherwise he wouldn't use the setting in the first place) but we break his intent. I'd rather show a warning instead of blocking his intent.

**Comment by phonzammi** [comment]
Right, it's just that if the user returns a pageContextPromise from onRenderHtml(), then they wouldn't have it.

**Comment by brillout** [comment]
Shall we merge?

**Comment by brillout** [comment]
> https://github.com/vikejs/vike/pull/1743/commits/8001eb19edba1fa3796e2963b85c35cd4c2fdb51

Good catch :ok_hand:

**Comment by phonzammi** [comment]
LGTM :rocket:

**Comment by brillout** [comment]
Merged :rocket:

**Comment by brillout** [comment]
I suggest we give #1740 another try and then release a new version. (The docs will be describing a feature that isn't released yet for a little while, but I think it's ok if we manage to merge/decide on 1740 sooner rather than later.)

**Comment by phonzammi** [comment]
Thank you very much :+1:

**Pull request merged**
