### PR TITLE
Update nextjs.page.server.mdx: Server/deployment agnostic

### PR DESCRIPTION
**Pull request by redbar0n**
To give a better overview of the state of things with Next.js, under the 'Server/deployment agnostic' section.

### CODE REVIEW

**Comment by brillout** [comment]
Neat. How about this?

```diff
- (which becomes pricey at scale).
+ (which is [known](some-link) to [be](some-other-link) very [expensive](maybe-even-third-link))
```

Also that Vecel's pricing is opaque. It's quite a big turn-off, and even a red flag for large enterprise.

**Comment by brillout** [comment]
> The community also made the framework-agnostic toolkit [SST](https://sst.dev/) to ease Serverless deployment to AWS in particular (since AWS infrastructure is a pain to deal with directly/non-programmatically). So SST [attempts to replicate](https://open-next.js.org/advanced/architecture) Vercel's infrastructure and ease-of-deployment for Serverless, in a free, open-source, and self-hostable manner. Open-Next is typically used with SST if deployed to AWS Lambda.

Correct me if I'm wrong, but I think this is more of a AWS issue than a Next.js one? E.g. you'd equally may want to use SST for deploying Vike to AWS. But maybe I'm missing something 👀

**Comment by brillout** [comment]
I did some minor changes, feel free to revert any of it. (Your writen language is esquiste btw. 👌)

**Comment by redbar0n** [comment]
Thanks. I implemented your suggestions. All should be resolved and ready to merge now.

**Comment by brillout** [comment]
Is [this change](https://github.com/vikejs/vike/pull/1415/commits/9f7cbf6ab36fff14f53c3c0b2e4c570281ba867a) ok for you?

**Comment by brillout** [comment]
As always: feel free to disagree with my other changes as well.

**Review by redbar0n — COMMENTED** [review]
Yes, that's fine. I mostly included it because I found it hard to differentiate OpenNext from SST. But SST is not so relevant to the comparison between Vike and NextJS, so it can be left out, for brevity.

**Pull request merged**
