### PR TITLE
Minor update examples/auth

### PR DESCRIPTION
**Pull request by phonzammi**
Minor refactor of examples/auth

Since onRenderHtml() of vike-react v0.3.4 has condition : [isSsrDisabled](https://github.com/vikejs/vike-react/blob/24ebe5902e7a86b2145af280574530098647f30c/vike-react/renderer/onRenderHtml.tsx#L36C3-L55C78)

If we don't create our own server/index.ts file (server entry if i am not mistaken), it will just works.

But if we do create custom server/index.ts (like in this example) then we have to return
[stream-pipe](https://vike-v1-staging.lourot.dev/stream#stream-pipes)
```
const { statusCode, headers, earlyHints } = httpResponse
if (res.writeEarlyHints) 
res.writeEarlyHints({ link: earlyHints.map((e) => e.earlyHintLink) })
headers.forEach(([name, value]) => res.setHeader(name, value))
res.status(statusCode)
httpResponse.pipe(res)
```
or [stream-to-string](https://vike-v1-staging.lourot.dev/stream#stream-to-string)
```
const body = await httpResponse.getBody()
      if (typeof body !== 'string') {
        return next()
      }
headers.forEach(([name, value]) => res.setHeader(name, value))
res.status(statusCode).send(body)
```

cmiiw
_**no need to merge in case of mess**_

### CODE REVIEW

**Comment by brillout** [comment]
Good catch 👍.

I'd use `.pipe()` so that we preserve the stream. The CI is failing; have a look at the warning printed there.

**Comment by phonzammi** [comment]
Thanks @brillout,
> I'd use .pipe() so that we preserve the stream

I'll change to .pipe().
> The CI is failing; have a look at the warning printed there.

I'm testing it on local right now

**Comment by phonzammi** [comment]
> The CI is failing

I've checked, I think it's failing to find [hasText: 'Neumann'](https://github.com/vikejs/vike/blob/74d84f54c2f024cd9b47b1fa7582dfb710003035/examples/auth/.testRun.ts#L24) 

by adding userAgent fixed it

**Comment by brillout** [comment]
Neat 💯

**Comment by brillout** [comment]
Looking forward to further PRs 💫

**Comment by phonzammi** [comment]
Thanks, I just learning & trying from little problem to be fixed, I hope I can help make a few good feature for vike ❤️

**Comment by brillout** [comment]
Sounds good 🙂. If you want we can create a new label `easy-contribution 🌱` along `contribution-welcome 💕`.

**Comment by phonzammi** [comment]
Well that would be nice, more specific for newbies like me

**Pull request merged**
