### PR TITLE
fix: improve `injectScriptsAt` condition handling

### LINKED ISSUE #1856: Issue with `injectScriptsAt: "STREAM"` when integrating SolidJS's `renderToStringAsync()` for crawlers.
### Description

When attempting to [add support for checking crawlers/bots & integrate renderToStringAsync()](https://github.com/vikejs/vike-solid/pull/117/commits/711742cae563fc888b064b8377a4c6a84d0b042d) to `vike-solid` in https://github.com/vikejs/vike-solid/pull/117. We encountered a bug: `You stumbled upon a Vike bug.`

```js
[17:05:52.522][/examples/solid-query][pnpm run dev][stderr] 5:05:52 PM [vike@0.4.193][request(2)][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at injectHtmlTagsToString (file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/runtime/html/injectAssets.js:15:5)
    at renderDocumentHtml (file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/runtime/html/renderHtml.js:38:32)
    at executeOnRenderHtmlHook (file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/runtime/renderPage/executeOnRenderHtmlHook.js:33:24)
    at renderPageAlreadyRouted (file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js:58:30)
    at renderPageNominal (file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/runtime/renderPage.js:284:36)
    at renderPageAlreadyPrepared (file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/runtime/renderPage.js:119:[45](https://github.com/vikejs/vike-solid/actions/runs/10742321893/job/29794694075?pr=117#step:8:46))
    at renderPageAndPrepare (file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/runtime/renderPage.js:99:12)
    at file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:54:35
    at renderPage (file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/runtime/renderPage.js:45:35)
    at file:///home/runner/work/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.193_vite@5.4.2_@types+node@22.4.0_terser@5.31.6_/node_modules/vike/dist/esm/node/plugin/shared/addSsrMiddleware.js:30:27
```

This issue occurs when we have a `+config.js` file like this:
```js +config.js
export default {
  stream: true,
  injectScriptsAt: "STREAM",
} satisfies Config;
```

We set `injectScriptsAt: "STREAM"`, but `renderToStringAsync()` returns a string, not a stream.

### PR DESCRIPTION
**Pull request by phonzammi**
fix #1856 

@brillout, 
This fix addresses issue #1856. Please feel free to reject this if you believe there is a better approach to resolve the issue.

### CODE REVIEW

**Comment by brillout** [comment]
That makes sense. How about `HTML_BEGIN` instead of `HTML_END`?

**Comment by brillout** [comment]
> > That makes sense. How about `HTML_BEGIN` instead of `HTML_END`?

> I'm sorry, what do you mean?

@phonzammi I mean that:

```diff
- return 'HTML_BEGIN'
+ return 'HTML_END'
```

**Comment by phonzammi** [comment]
That works too. I just prefer using `HTML_BEGIN`

**Comment by brillout** [comment]
I've improved the comments.

**Comment by brillout** [comment]
I'll pre-release in a moment.

**Comment by phonzammi** [comment]
Thank you, no rush 👍

**Comment by brillout** [comment]
Released as `0.4.195`.

**Pull request merged**
