### PR TITLE
Remove ?extractAssets workaround in favor of build.ssrEmitAssets

### PR DESCRIPTION
**Pull request by nitedani**
Implements https://github.com/vikejs/vike/issues/1339.

### CODE REVIEW

**Comment by nitedani** [comment]
Is this the right direction?

**Comment by brillout** [comment]
I think it's easier if we inject the server manifest into the client manifest [here](https://github.com/vikejs/vike/blob/86d6558eb0ea0716b0f349af4cf6c35f7c3e2acd/vike/node/plugin/plugins/buildConfig.ts#L69-L78). That way, the rest of Vike's code will work as it does today, e.g. no need to modify `node/runtime/globalContext.ts` then. Atually, if we keep `dist/assets.json` semantically equivalent, then I think we don't need to modify the server runtime at all.

**Comment by brillout** [comment]
I'm reading `ssrEmitAssets.ts` right now, and I'm seeing logic to merge manifests. So I guess you already tried to merge the server manifest into `dist/assets.json` and have things "just work".

Still, I don't think we need to adapt the server runtime (nor the pre-rendering code) if we keep `dist/assets.json` semantically equiavelent. (More precisely speaking, all we need to do is to remove the `?extractAssets` handling from the server runtime, which you seem to have already done.)

**Comment by brillout** [comment]
AFAICT, if we do a clever merging instead of just a "dumb"  `{ ...clientManifestParsed, ...serverManifestParsed }`, then we can keep `assets.json` semantically equivalent and, therefore, alleviate ourselfes the need to adapt the server runtime.

So I guess the question is this: can we make the merging so clever that evertyhing else just works as before? A lot of Vite frameworks use `ssrEmitAssets`; a GitHub search for "ssrEmitAssets" would point to a lot of code to copy from.

**Comment by brillout** [comment]
LGTM, let me know if for you as well then I'll merge.

Looking forward to further resolve all blockers and merge the worker server PR ✨

**Comment by nitedani** [comment]
Looks good, works for me.

**Pull request merged**
