### PR TITLE
docs: add new react-query integration example

### PR DESCRIPTION
**Pull request by AurelienLourot**
See vikejs/vike-react#30

FYI @phonzammi

### CODE REVIEW

**Comment by AurelienLourot** [comment]
Is it me or some tests have become more flaky recently?

**Comment by brillout** [comment]
I'm aware of this one flakiness; I did dig into it yet because it occurred only very seldomly. 

> more flaky recently

Yea it's being a couple of weeks I have the same impression. Maybe something changed with GitHub's Actions.

**Comment by brillout** [comment]
@AurelienLourot So far I was pushing new examples at the top of lists, I'm not sure which way is the best. As you wish.

**Comment by AurelienLourot** [comment]
makes sense! I've reordered and pushed directly to main. Hope that's OK

**Comment by brillout** [comment]
Totally 💯

**Pull request merged**
