### PR TITLE
i18n doc: pass query params to 'urlLogical'

### PR DESCRIPTION
**Pull request by lebretont**
Pass the query parameters to 'urlLogical' in the i18n doc.
So the pages can access the parameters.

### CODE REVIEW

**Comment by brillout** [comment]
Isn't it implicit that `extractLocale()` would preserve it?

I'm inclined to not add a note about this because as it would dilute the core message of the docs.

Closing but feel free to continue discussing this.

**Comment by lebretont** [comment]
> Isn't it implicit that `extractLocale()` would preserve it?
> 
> I'm inclined to not add a note about this because as it would dilute the core message of the docs.
> 
> Closing but feel free to continue discussing this.

`extractLocale()` doesn't preserve it because we are using `urlPathname`.
Only `urlOriginal` has the query params

**Comment by brillout** [comment]
Indeed. How

**Comment by brillout** [comment]
How about this?

**Comment by brillout** [comment]
FYI `pageContext.urlParsed` is going to be renamed `pageContext.url` is the next major release.

**Comment by lebretont** [comment]
Cleaner than mine!

**Comment by brillout** [comment]
Merged :tada: Thank you for the PR and pushing through despite my initial push back.

(In case it's an option for your company: we're looking for [sponsors](https://github.com/vikejs/vike/issues/1350).)

**Pull request merged**
