### PR TITLE
show import errors in dev

### PR DESCRIPTION
**Pull request by nitedani**
Related: https://github.com/vikejs/vike/issues/621

Show helper message in dev.

### CODE REVIEW

**Comment by nitedani** [comment]
I need some help with showing the error message, snippet, and the original error below them.
https://github.com/vikejs/vike/pull/1358/files#diff-52c661a478f000a8c948b903364849179409ab4986372eadd14f8f0c76012631R20-R28

**Comment by brillout** [comment]
Neat 💯

How about we wrap [`viteDevServer.ssrLoadModule(virtualFileIdImportUserCodeServer)`](https://github.com/vikejs/vike/blob/9a3ac5afc806701af3aee467674c74cd5e0acb89/vike/node/runtime/page-files/setup.ts#L13) instead? I guess that would catch the same exceptions?

As for production, we can catch exceptions thrown by [`await loadServerBuild(outDir)`](https://github.com/vikejs/vike/blob/9a3ac5afc806701af3aee467674c74cd5e0acb89/vike/node/runtime/globalContext/loadImportBuild.ts#L23).

We can also catch exceptions thrown by [`await hookFnCaller()`](https://github.com/vikejs/vike/blob/9a3ac5afc806701af3aee467674c74cd5e0acb89/vike/shared/hooks/executeHook.ts#L69) such as React's infamous `Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`. (I wrote a React patch a while ago to make debugging this React error much easier; I'll see if I can find it again and polish it.)

**Comment by nitedani** [comment]
[viteDevServer.ssrLoadModule](https://github.com/vikejs/vike/blob/9a3ac5afc806701af3aee467674c74cd5e0acb89/vike/node/runtime/page-files/setup.ts#L13)
doesn't throw any errors

I've found no other way to catch these errors.

**Comment by brillout** [comment]
In principle, the error must/should be catched somewhere by Vike, otherwise
Vike wouldn’t be able to show the error page.

In other words: if the error leads to the error page to be rendered then we
have, de facto, the opportunity to catch the error in Vike Land. (Although
make sure the error page exists, otherwise Vike has no error page to
render.)

**Comment by brillout** [comment]
Notable changes:
 - https://github.com/vikejs/vike/pull/1358/commits/df9423bebcbbf625dd25b7ce3559f187212e3878
 - https://github.com/vikejs/vike/pull/1358/commits/52a11ca2ea3aa16e267b9f8ab6d6c4a02fb956cb

The rest is mostly just some minor refactoring.

Let me know if you object with any of the changes, otherwise I'll merge 🎉

**Comment by nitedani** [comment]
onRuntimeError is not called, it stops here: https://github.com/vikejs/vike/pull/1358/files#diff-7fb721f8b206cd2db4fc64bbf0c4e005aac41836d50d66133acc17b019255d1cR114

**Comment by brillout** [comment]
I actually realized I forgot to try my changes 😅

> onRuntimeError is not called, it stops here: https://github.com/vikejs/vike/pull/1358/files#diff-7fb721f8b206cd2db4fc64bbf0c4e005aac41836d50d66133acc17b019255d1cR114

Let me have a look.

**Comment by brillout** [comment]
I just had a quick look. Vike treats the error as transpilation error and thus doesn't trigger `onRuntimeError()`. Let me fix this.

**Comment by brillout** [comment]
@nitedani Alright, I think it's good now. Shall we merge?

(I'll double check if we missed something from the list later today. Other than that, the PR LGTM now.)

**Pull request merged**
