### PR TITLE
Create example page of Mantine

### PR DESCRIPTION
**Pull request by Kenzo-Wada**
Discussion from Discord: https://discordapp.com/channels/1105779924658303058/1105781552719331371/1181247050646564905

Created example Page for Mantine Template which I made.

Screenshot from 2023-12-05 19-37-22

### CODE REVIEW

**Comment by brillout** [comment]
Neat 👍 One thing: we can remove the `vite-plugin-ssr` note because your example already uses the Vike rebrand.

**Comment by Kenzo-Wada** [comment]
@brillout 

thankyou for the review! fixed at [9846cfe](https://github.com/vikejs/vike/pull/1315/commits/9846cfe102fef22387fc457918981bbea2d6259d), and updated the screenshot!

**Comment by brillout** [comment]
Perfect 👍 One last thing: we should remove the `fix: ` and `feature: ` prefixes otherwise these commits will wrongfully be included in `CHANGELOG.md`.

**Comment by Kenzo-Wada** [comment]
sorry for that... i've fixed the commit message!

**Comment by brillout** [comment]
Merged 🎉

**Pull request merged**
