### PR TITLE
docs: add note about community page

### LINKED ISSUE #1967: Add note about community page
### Description

Let's add this note to all tool integration pages:

```mdx
<Contribution>
  This page is community-led and may contain outdated information. PR welcome to update/improve this page.
</Contribution>
```

@phonzammi Up for the task?

### PR DESCRIPTION
**Pull request by phonzammi**
closes #1967 

@brillout, Please take a look and review this PR

### CODE REVIEW

**Comment by brillout** [comment]
- I meant the tool pages (i.e. the pages listed at https://vike.dev/examples), not the integration guides. The integration guides aren't community driven.
- Let's re-use the component instead of duplicating it. Intervention++.

**Comment by brillout** [comment]
Perfect! Just one little stylistic thing: let's add an empty line after `<CommunityNote>`.

**Comment by brillout** [comment]
> Perfect! Just one little stylistic thing: let's add an empty line after `<CommunityNote>`.

Self-merge welcome then.

**Comment by phonzammi** [comment]
Thank you, merging now

**Pull request merged**
