### PR TITLE
Add E2E tests for the behavior of `config.meta.<setting>.env`, `.cumulative` and `.effect`

### PR DESCRIPTION
**Pull request by cr7pt0gr4ph7**
## Rationale
I couldn't find any tests that specifically tested the configuration inheritance mechanism as well as the ordering of inherited cumulative settings, so I've taken the liberty to implement those myself, in preparation for possible further improvements (see e.g. #1692 as well as some type inference improvements related to `config.meta` I intend to contribute).

I've chosen to go with an E2E test here to be able to exercise the build-time logic configuration merging & serialization logic as well. There might be prettier ways to do this, but it gets the job done and covers the user-observable behavior.

### CODE REVIEW

**Comment by brillout** [comment]
It's actually something I've been wondering: whether it's worth it to test it.

**Comment by brillout** [comment]
So far I'm inclined to say it isn't worth it. But I'll have a closer look at your tests.

**Comment by cr7pt0gr4ph7** [comment]
> It's actually something I've been wondering: whether it's worth it to test it.

As a user of Vike in one of my projects, I'd say definitely yes. It's such a fundamental part of Vike which has its own complexities (especially when something like `inherit: false` or cumulative settings with groups are going to be implemented) and is possibly security-relevant (when an `env: { server: true }` setting that should not be exposed to clients is unintentionally exposed, which you won't notice in applications because it wouldn't break anything) that I was surprised to not see any tests of it.

**Comment by brillout** [comment]
I'm actually going to work on code related to config handling this week. So it's a good time to add inheritance tests. I'll have a closer look at this PR today/tomorrow (looks good at first sight).

**Comment by brillout** [comment]
The `test/playground` is getting quite big; some refactoring will help maintain it.
 - Move the tests inside `pages/**/*` so that `.testRun.ts` only imports a bunch of functions and executes these functions. In other words: no test logic is directly defined inside `.testRun.ts`.
 - Move `serializeSettings()` inside a new directory `utils/` at the root of the app.
 - Make `serializeSettings()` generic e.g. `serializePageContextProps(pageContext, props: string[])`.
 - Define the the serializing logic `serializeSettings()` and it's parsing counterpart inside the same file.
 - Move `isBrowser.ts` inside `utils/`.

Looking forward to it. It's going to make test/playground a neat testbed.

**Comment by cr7pt0gr4ph7** [comment]
> The `test/playground` is getting quite big; some refactoring will help maintain it.
> [...]

Done :+1: A bit of care has to be taken to not import `@brillout/test-e2e` in files like `serializeSettings.ts` that are shared between the test code and the code-under-test. `@brillout/test-e2e` will try to parse the command line options as soon as it's loaded - which causes it to throw an error if one tries to run the code-under-test separately with e.g. `pnpm run dev --host`.

**Comment by cr7pt0gr4ph7** [comment]
@brillout: The last CI failures where due to the screenshot tests, which this PR should not even have touched upon. I tried to reproduce the issues locally, but couldn't find expected screenshots that the CI compares against...

**Comment by brillout** [comment]
Awesome, collocating is a major improvement. Reading your new tests is now a breeze :sparkles:. I left a final polishing review, let's merge after that.

**Comment by brillout** [comment]
Thank you @cr7pt0gr4ph7 for your contribution :green_heart:

**Pull request merged**
