### PR TITLE
fix: improve addSsrMiddleware() condition

### PR DESCRIPTION
**Pull request by phonzammi**
@brillout 

Let me try this with '@hono/vite-dev-server' first.
I'll try to add a test later.

Cmiiw and Let me know if you have anything else to add.

### CODE REVIEW

**Comment by brillout** [comment]
LGTM! AFAICT this can be merged as-is.

> Let me try this with '@hono/vite-dev-server' first.

:+1: Let me know if it works then let's merge & (pre-)release.

> I'll try to add a test later.

No need to.

**Comment by phonzammi** [comment]
Yes, it works

**Comment by brillout** [comment]
Nice, I’ll merge & release tomorrow.

**Comment by brillout** [comment]
Preleased as `0.4.171-commit-3b2cb88`, but let me know if you prefer a stable release.

**Comment by phonzammi** [comment]
Thanks @brillout

**Pull request merged**
