### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Found a sea of misspellings.

@brillout Please consider using https://github.com/crate-ci/typos everywhere.

All the best to you!

### CODE REVIEW

**Comment by brillout** [comment]
Thank you :green_heart:

The CI is red, it seems that the source code changes aren't consistent?

> Please consider using https://github.com/crate-ci/typos everywhere.

Up for a PR? You can fork the repository to test your CI changes.

**Comment by szepeviktor** [comment]
> > Please consider using https://github.com/crate-ci/typos everywhere.
> 
> Up for a PR?

I let you add typos to CI: `uses: crate-ci/typos@master`

`.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
    "CHANGELOG.md",
    "examples/i18n/locales/translations.js",
    "test-deprecated-design/i18n/locales/translations.js",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\[[0-9a-f]{7}\\]",
    "scss\\|styl\\|stylus",
]
```

**Comment by brillout** [comment]
Thinking of it, it's best we only fix the typos for the documentation. The source code typo fixes would induce a lot of merge conflicts for the pending PRs and branches.

**Comment by szepeviktor** [comment]
Now you have the tools. Please revert any directory you wish.

**Comment by brillout** [comment]
Closing in favor of https://github.com/vikejs/vike/issues/1836. Thank you for getting this started!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by brillout** [comment]
Follow up: https://github.com/vikejs/vike/pull/1839.

**Comment by FlorianCassayre** [comment]
Related #1238

**Pull request closed without merging**
