### PR TITLE
Fallback to default injectToStream when react-streaming stream is closed

### PR DESCRIPTION
**Pull request by magne4000**
Fixes https://github.com/batijs/bati/issues/283

PS: I'm not sure why imports are reordered, it's disabled in my IDE (perhaps biome does that?)

### CODE REVIEW

**Comment by brillout** [comment]
This would await for the stream to completely end though, see docs about `streamEnd` at https://github.com/brillout/react-streaming.

Thus, this will probably break [progressive rendering](https://vike.dev/streaming#progressive-rendering). You can test that at `/examples/react-streaming`. (We should probably add some progressive rendering tests at some point.)

> PS: I'm not sure why imports are reordered, it's disabled in my IDE (perhaps biome does that?)

There isn't any automatic formatting, so I'm inclined to think it's something on your side.

**Comment by magne4000** [comment]
Yup I noticed that's not the fix we need, we would need a way to check if the underlying `streamOriginal` is closed, but I'm not sure we have that available

**Comment by brillout** [comment]
I wonder why and who is trying to push to the stream even though it's
already closed.

**Comment by magne4000** [comment]
Looking at the log, I would say Vike itself or Vite:
```
Error: [react-streaming@0.3.29][Wrong Usage] Cannot inject following chunk after stream has ended: `<script id="vike_pageContext" type="application/json">{"$$typeof":"!undefined","abortReason":"!undefined","_urlRewrite":null,"_urlRedirect":"!undefined","abortStatusCode":"!undefined","_abortCall":"!undefined","_pageContextInitIsPassedToClient":"!undefined","_pageId":"/pages/_error","routeParams":{},"data":"!undefined","pageProps":{"is404":false},"is404":false,"_isServerSideError":"!undefined"}</script><script type="module" async>
import RefreshRuntime from "/@react-refresh"
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
import "/@vite/client";
import "/@fs/tmp/bati-app/node_modules/.pnpm/vike@0.4.177_react-streaming@0.3.29_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.3.1_@types+node@20.14.9_/node_modules/vike/dist/esm/client/client-routing-runtime/entry.js";
</script>`
    at injectToStream (/tmp/bati-app/node_modules/.pnpm/react-streaming@0.3.29_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-streaming/dist/cjs/server/renderToStream/createBuffer.js:12:33)
    at injectHtmlFragment (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.177_react-streaming@0.3.29_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.3.1_@types+node@20.14.9_/node_modules/vike/dist/esm/node/runtime/html/injectAssets/injectHtmlTags.js:48:9)
    at file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.177_react-streaming@0.3.29_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.3.1_@types+node@20.14.9_/node_modules/vike/dist/esm/node/runtime/html/injectAssets/injectHtmlTags.js:16:26
    at Array.forEach (<anonymous>)
    at injectHtmlTags (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.177_react-streaming@0.3.29_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.3.1_@types+node@20.14.9_/node_modules/vike/dist/esm/node/runtime/html/injectAssets/injectHtmlTags.js:10:15)
    at injectToHtmlBegin (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.177_react-streaming@0.3.29_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.3.1_@types+node@20.14.9_/node_modules/vike/dist/esm/node/runtime/html/injectAssets.js:41:17)
    at injectAtStreamBegin (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.177_react-streaming@0.3.29_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.3.1_@types+node@20.14.9_/node_modules/vike/dist/esm/node/runtime/html/injectAssets.js:25:21)
    at injectStringAtBegin (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.177_react-streaming@0.3.29_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.3.1_@types+node@20.14.9_/node_modules/vike/dist/esm/node/runtime/html/renderHtml.js:68:24)
```

**Comment by brillout** [comment]
This chunk is indeed authored by Vike (not Vite).

Both Vike (`DEBUG=vike:stream`) and react-streaming (https://github.com/brillout/react-streaming/commit/c98b1a58119e2aa917d010dfdb31e15c66d1743a) have debug logs to see what happens when. It's usually an effective way to get to the bottom of these kind of issues. But let me know if you want me to have a look at it.

**Comment by magne4000** [comment]
> But let me know if you want me to have a look at it.

Could be great yes.

I'm not sure if the stream created by `react-streaming` in `createReadableWrapper` should be kept open until further notice (but what does it even mean in this case? and how does this then apply to other frameworks supporting streaming?).

Intuitively, I would have `injectToStream` be a wrapper around any underlying Stream, but it would ignore close (non-error) events from underlying stream (i.e. React stream), and only listen for close events coming from "above" (i.e. Vike or Vite, I'm confused here).

**Comment by brillout** [comment]
How can I reproduce the issue?

**Comment by magne4000** [comment]
For now I was testing with those instructions https://github.com/batijs/bati/issues/283#issuecomment-2194448517

**Comment by magne4000** [comment]
I tried with `stream: 'node'` and:
```ts
// vike-handler.ts
import { Writable } from 'node:stream';
...
const { readable, writable } = new TransformStream();

response?.pipe(Writable.fromWeb(writable));

return new Response(readable, {
  status: response?.statusCode,
  headers: response?.headers,
});
...
```

and no error, so at least it's contained to Web streams mode.

**Comment by magne4000** [comment]
> For now I was testing with those instructions [batijs/bati#283 (comment)](https://github.com/batijs/bati/issues/283#issuecomment-2194448517) (and fiddling directly in node_modules)

I disabled stream mode by default in Bati, so you perhaps need to manually add `stream: 'web'` back to `+config.ts`

**Comment by magne4000** [comment]
Weirdly enough, if I try to copy the reproduction repo in `vike/examples` I have no issue (but streaming seems disabled) :confused:

**Comment by brillout** [comment]
:+1: I'll have a look.

**Comment by magne4000** [comment]
> Weirdly enough, if I try to copy the reproduction repo in `vike/examples` I have no issue (but streaming seems disabled) 😕

:face_with_head_bandage: I was testing on this branch with my "fix"...

Anyway, I pushed the repo in `vike/examples/bati-app` for testing purpose.

**Comment by brillout** [comment]
I can reproduce.

**Comment by brillout** [comment]
Actually, I cannot reproduce anymore.

Neither on this PR nor on https://github.com/brillout/vike-stream-bug-2024-06. Can you systematically reproduce or is it random?

**Comment by brillout** [comment]
I just pushed [this tentative fix](https://github.com/vikejs/vike/commit/4973eec875122a1d114c0bf49321fd32871095fb) on [`brillout/dev`](https://github.com/vikejs/vike/commits/brillout/dev). I'm shooting in the dark as I cannot reproduce; let me know if it fixes the issue (you can test the fix by rebasing this PR onto `brillout/dev`).

**Comment by magne4000** [comment]
> Actually, I cannot reproduce anymore.
> 
> Neither on this PR nor on https://github.com/brillout/vike-stream-bug-2024-06. Can you systematically reproduce or is it random?

Yup still reproduce, even managed to reproduce on a second machine

> I just pushed [this tentative fix](https://github.com/vikejs/vike/commit/4973eec875122a1d114c0bf49321fd32871095fb) on [brillout/dev](https://github.com/vikejs/vike/commits/brillout/dev). I'm shooting in the dark as I cannot reproduce; let me know if it fixes the issue (you can test the fix by rebasing this PR onto brillout/dev).

I'll try that

**Comment by magne4000** [comment]
After a quick `pnpm dedupe`, it at first seems to have fixed the issue. But it generates an interesting side effect on the client:
image

The added code after the stream closes makes React confused when trying to rehydrate on the client.

**Comment by brillout** [comment]
That's actually something I was expecting, let me try to reproduce on my machine.

**Comment by brillout** [comment]
I can reproduce. Let me dig & fix.

**Comment by brillout** [comment]
I believe https://github.com/vikejs/vike/pull/1722 fixes it.

I ain't sure because [I couldn't reproduce the error without the fix](https://github.com/vikejs/vike/pull/1722/commits/586735a5148651062f7b6c5940b8cba15bcc4f47). But we can be confident this works if: you can reproduce the error by reverting the fix, then re-apply the fix and then not be able to reproduce the error.

**Comment by magne4000** [comment]
I do not have issues anymore on #1722 but how can I make sure that streaming is actually working?

**Comment by brillout** [comment]
With working do you mean that it doesn't throw the error anymore or that [progressive rendering](https://vike.dev/streaming#progressive-rendering) works?

**Comment by magne4000** [comment]
> With working do you mean that it doesn't throw the error anymore or that [progressive rendering](https://vike.dev/streaming#progressive-rendering) works?

The I have no error, but I'm not sure I have progressive rendering, what's the best way to test it?

**Comment by brillout** [comment]
FYI `DEBUG=vike:stream,react-streaming:buffer` can be quite helpful.

**Comment by magne4000** [comment]
@brillout progressive rendering works both with Node Stream and Web Stream with latest `vike-react` and `vike-streaming` :rocket:

**Comment by brillout** [comment]
Even with the universal adapter? :eyes:

**Comment by magne4000** [comment]
Yes, that is what I was testing with my latest push https://github.com/vikejs/vike/pull/1718/commits/0cc3cbca61c5d6ab88eb0336c36453fe7593a9ec

**Comment by brillout** [comment]
Nice :rocket:

**Comment by magne4000** [comment]
@brillout I guess that a proper fix requires only to bump `vike-react` and `vike-streaming`. Do you want me to create another PR for that?

**Comment by brillout** [comment]
Hm, that's surprising as I think #1722 is required to avoid the race condition. There wasn't any fix regarding the race condition error in `react-streaming` nor `vike-react`.

How about this: we merge 1722 in the hope it fixes the error, then let's have a look at it again if a user complains.

I'm working on a `react-streaming` feature right now, then I'll merge 1722.

**Comment by brillout** [comment]
Fixed at https://github.com/vikejs/vike/pull/1722 and released in `0.4.178`.

**Pull request closed without merging**
