### PR TITLE
feat: add configuration for typos-rs-npm and update formatting scripts

### PR DESCRIPTION
**Pull request by IanWorley**
I have add the spell checker as you requested. I would like to know would you like me to expose the Github_Token to the workflows? What other configurations would like done to the typos? 

#1943

### CODE REVIEW

**Comment by brillout** [comment]
Neat :sparkles:

> I would like to know would you like me to expose the Github_Token to the workflows?

What GitHub token? What is it used for?

> What other configurations would like done to the typos?

Can we set `--files ./docs/*` inside `_typos.toml` instead?

I think we need to add `**/dist/` to the ignore list.

Instead of adding it to the `format` script let's create two new npm scripts `spellcheck` and `spellcheck:check`, and let's create a new CI job for it. It's nice to see in the CI overview what exactly is failing.

**Comment by IanWorley** [comment]
@brillout My reasoning to expose the github_token was to reduce the odds of being ratelimt which could disrupt the github action workflow when trying to download typos package from github. I do not think it is possible to select the directory for typos to spell check. There is only ways to exclude files in _typos.toml file. And in my current changes I have added a new github action for typos

**Comment by brillout** [comment]
> My reasoning to expose the github_token was to reduce the odds of being ratelimt which could disrupt the github action workflow when trying to download typos package from github.

I see. Yes, I guess we can add it publicly for now and add it privately if it's an issue to have it public. I guess we can always generate a new one?

The PR LGTM. The only thing is that the CI seems to be failing, ideas why? It seems like it doesn't work on windows?

**Comment by IanWorley** [comment]
@brillout As of right now I do not know why pnpm is stuck on windows.

**Comment by brillout** [comment]
Since we have `"typos-rs-npm": "github:dalisoft/typos-rs-npm"` in `devDependencies`, couldn't we do `typos-rs-npm --files ./docs/*` instead of `pnpx github:dalisoft/typos-rs-npm --files ./docs/*`?

**Comment by brillout** [comment]
> @brillout As of right now I do not know why pnpm is stuck on windows.

I don't have a windows machine to try it out. Feel free to push experimental commits in this PR to see what causes the CI to hang.

**Comment by brillout** [comment]
Let's close in favor of tracking:
 - https://github.com/crate-ci/typos/issues/1188
 - https://github.com/dalisoft/typos-rs-npm/issues/48

**Comment by brillout** [comment]
Let's re-open (hopefully soon) after one of these two resolves.

**Comment by brillout** [comment]
I'm now using:
```json
    "spellcheck": " cd ./packages/vike.dev/ && pnpm dlx github:dalisoft/typos-rs-npm --write-changes",
```

This does the trick for now.

No need for `spellcheck.toml` for now since `node_modules/`, `.git/`, and `dist/` are already skipped by default.

**Comment by brillout** [comment]
We can easily add it to the CI if https://github.com/crate-ci/typos/issues/1321 is implemented.

**Comment by brillout** [comment]
Whole repo is now spell checked:
 - https://github.com/vikejs/vike/pull/2509
 - https://github.com/vikejs/vike/pull/2510

**Pull request closed without merging**
