### PR TITLE
fix: don't glob page files in dist/

### PR DESCRIPTION
**Pull request by AurelienLourot**
(attempt to solve #1189)

@brillout @robinelvin with this small patch, an empty `dist/foo/bar.page.js` file doesn't get globbed anymore. Validated with `pnpm run dev|preview|build`, however with `build` there seems to still be a problem, as it fails with

```
vike v0.4.143 pre-rendering HTML...
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
    at Xc (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:77:77)
    at Z (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
    at Yc (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
    at Xc (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:73:145)
    at Z (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
    at Yc (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
    at Xc (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:73:145)
    at Z (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
    at Xc (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:481)
    at Z (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
 ELIFECYCLE  Command failed with exit code 1.
```

Still digging on my own but @brillout please let me know if this rings a bell too. Thanks!

### CODE REVIEW

**Comment by brillout** [comment]
👍 This works for the current design but, if I ain't mistaken (correct me if I'm wrong), we don't have access to Vite's config with the V1 design (see the `fast-glob` usage in `getVikeConfig.ts`).

We could still merge but, on the other hand, this means the V1 design will be regression for a couple of users.

**Comment by brillout** [comment]
As for the React issue, it's one of these painful React issues that is unfortunately quite hard to debug. I don't think / I wouldn't know how it's related to your PR.

**Comment by brillout** [comment]
FYI this React error happens quite often because of CJS/ESM issues, e.g. if you import `undefined` instead of the actual component.

**Comment by AurelienLourot** [comment]
> if I ain't mistaken (correct me if I'm wrong), we don't have access to Vite's config with the V1 design (see the `fast-glob` usage in `getVikeConfig.ts`).

I'll have a look at that :)

> As for the React issue, it's one of these painful React issues that is unfortunately quite hard to debug. I don't think / I wouldn't know how it's related to your PR.

It doesn't happen if I delete the my empty `dist/foo/bar.page.js`. What I'm trying to achieve here is that files outside `dist/client/` and `dist/server/` like this one shouldn't impact us at all, no matter how wrong they are. I'm not sure why this file gets picked up as it's now not part of the glob results

**Comment by brillout** [comment]
There is also Vite's `import.meta.glob` usage in `getVirtualFileImportUserCode.ts` which may explain this. (This is only used by current design; the V1 design only uses `fast-glob`.)

**Comment by AurelienLourot** [comment]
Indeed the culprit was `import.meta.glob`. I've just pushed a fix for that. So now it seems to work well with the current (non-V1) design, as in: dummy page files under `dist/` aren't picked up anymore.

> if I ain't mistaken (correct me if I'm wrong), we don't have access to Vite's config with the V1 design (see the `fast-glob` usage in `getVikeConfig.ts`).

I still would like to have a look at that

**Comment by AurelienLourot** [comment]
I have now solved the problem for V1 in exactly the same way: `config.build.outDir` was available everywhere needed. Validated locally with an empty `dist/+dummy.ts` file. Without this patch, `pnpm run build|dev` would fail. With this patch the dummy file doesn't get globbed and the build succeeds.

I'm quite happy with this PR now

**Comment by AurelienLourot** [comment]
The posix path failure on Windows is caused by me. Digging

**Comment by AurelienLourot** [comment]
Looks good now :)

**Comment by brillout** [comment]
Neat, I'm positively surprised `getVikeConfig()` is able to require Vite's `config`.

Let me think through if I can foresee an issue with the upcoming `vike.config.h.js`.

**Comment by brillout** [comment]
I think we're good.

Exciting. It has been a recurring pain for users &mdash; I'm very glad it's fixed now ✨

Let me review/polish some details.

**Comment by brillout** [comment]
Alright, did some refactoring to `getOutDirs.ts`. (Still dirty but it's slowly getting slightly cleaner, at least not *as* dirty as it used to be :-). FYI I added the many assertions to get the whole thing under control as it's an intricate set of interactions with Vite's config.)

**Comment by brillout** [comment]
Thanks for the PR! I'm super excited about this: one pain less for many users 👌.

Btw. I think https://github.com/vikejs/vike/issues/818 is now implementable.

**Comment by AurelienLourot** [comment]
Your last changes seem to have broken it, let me have a look

**Pull request merged**
